#! /bin/bash
echo $(date) $0 "$@" >>/tmp/bcsuv.log

function failed {
    echo "FAILED" >&2
    exit 100
}
trap failed ERR

if [ $# -eq 2 ]; then
    S="$1"
    T="$2"
elif [ $# -eq 1 ]; then
    S="$1"
    T="$1".aes
    DEL_S=1
else
    echo Usage: $0 "<filename>" "<target_dir|filename.aes>" >&2
    exit 1
fi

if [ -d "$T" ]; then
    T="$T"/"$(basename $S)".aes
fi
if [ -e "$T" ]; then
    echo "$T laready exists" >&2
    exit 2
fi

resource-fork-remove "$S"
# echo $HOME/bin/bcs -ce "$S" "$T" >&2
$HOME/bin/bcs -ce "$S" "$T"

if [ -n "$DEL_S" ]; then
    rm "$S"
fi
